# Generated by Django 5.2.7 on 2025-10-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
